sudo: false
language: node_js
node_js:
  - "6"
  - "8"

cache:
  directories:
    - "node_modules"

install:
  - npm install -g gulp-cli typescript
  - npm install

script:
  - npm run build

notifications:
  email:
    - jonasyuk@gmail.com
    - yujo2@oocl.com